Add flag to optionally include (or exclude) source code snippets
ekataglobal/clj-bugsnag pull request #14
Opened 2021-06-08 00:05 UTC by kevonavin

2021-06-08 18:33 UTC, imrekoszo approved these changes

2021-06-09 08:17 UTC, imrekoszo requested changes
I just noticed that there's an older PR which fully qualifies dependencies: https://github.com/ekataglobal/clj-bugsnag/pull/13

I think that could be merged to this one and its changes propagated to deps.edn

2021-06-09 15:27 UTC, imrekoszo approved these changes

2021-06-10 14:27 UTC, imrekoszo approved these changes

2021-06-10 14:48 UTC, janosmeszaros approved these changes

2021-06-10 14:48 UTC, merged